# -*- coding: utf-8 -*-
"""RefactorWineQuality.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ws_5SMlNBbVIs1ktZoCZ431Dxa7n9_7p
"""

import pandas as pd

df = pd.read_csv('winequality-red.csv',sep=';')
df.head()

df.columns = [label.replace(' ','_') for label in df.columns]
df.head()

def numeric_to_buckets(df, column_name):
  median = df[column_name].median()
  for i, val in enumerate(df[column_name]):
    if val >= median:
      df.loc[i, column_name] = 'high'
    else:
      df.loc[i, column_name] = 'low'

for feature in df.columns[:-1]:
  numeric_to_buckets(df, feature)
  print(df.groupby(feature).quality.mean(), '\n')